[book]
authors = ["Corbin"]
language = "en"
multilingual = false
src = "src"
title = "brismu: a relational interpretation of Lojban"

[preprocessor.metamath]
command = "python preprocess.py"
# Include tables before linkifying them.
after = ["links"]

[preprocessor.graphviz]
# Required for including DOT into Markdown.
after = ["links"]

[preprocessor.admonish]
command = "mdbook-admonish"

[output.html]
additional-css = ["./mdbook-admonish.css"]
